import { Unit } from './types';

export const UNITS: Unit[] = [
  { code: "TOTAL_HN", name: "D?ng b? Th�nh ph? H� N?i (T?NG H?P)" },
  { code: "DV001", name: "D?ng b? c�c co quan d?ng Th�nh ph?" },
  { code: "DV002", name: "D?ng b? UBND Th�nh ph?" },
  { code: "DV003", name: "D?ng b? C�ng an Th�nh ph?" },
  { code: "DV004", name: "D?ng b? B? Tu l?nh Th? d�" },
  { code: "DV005", name: "D?ng b? c�c Tru?ng D?i h?c, Cao d?ng" },
  { code: "DV006", name: "D?ng b? D?i h?c Qu?c gia H� N?i" },
  { code: "DV007", name: "D?ng b? Phu?ng Ba D�nh" },
  { code: "DV008", name: "D?ng b? Phu?ng B?ch Mai" },
  { code: "DV009", name: "D?ng b? Phu?ng B? D?" },
  { code: "DV010", name: "D?ng b? Phu?ng C?u Gi?y" },
  { code: "DV011", name: "D?ng b? Phu?ng C?a Nam" },
  { code: "DV012", name: "D?ng b? Phu?ng Chuong M?" },
  { code: "DV013", name: "D?ng b? Phu?ng Duong N?i" },
  { code: "DV014", name: "D?ng b? Phu?ng D?i M?" },
  { code: "DV015", name: "D?ng b? Phu?ng D?nh C�ng" },
  { code: "DV016", name: "D?ng b? Phu?ng D?ng Da" },
  { code: "DV017", name: "D?ng b? Phu?ng D�ng Ng?c" },
  { code: "DV018", name: "D?ng b? Phu?ng Gi?ng V�" },
  { code: "DV019", name: "D?ng b? Phu?ng H� D�ng" },
  { code: "DV020", name: "D?ng b? Phu?ng Hai B� Trung" },
  { code: "DV021", name: "D?ng b? Phu?ng Ho�n Ki?m" },
  { code: "DV022", name: "D?ng b? Phu?ng Ho�ng Li?t" },
  { code: "DV023", name: "D?ng b? Phu?ng Ho�ng Mai" },
  { code: "DV024", name: "D?ng b? Phu?ng Hung H�" },
  { code: "DV025", name: "D?ng b? Phu?ng Ki?n Hung" },
  { code: "DV026", name: "D?ng b? Phu?ng Kim Li�n" },
  { code: "DV027", name: "D?ng b? Phu?ng Khuong D�nh" },
  { code: "DV028", name: "D?ng b? Phu?ng L�ng" },
  { code: "DV029", name: "D?ng b? Phu?ng Linh Nam" },
  { code: "DV030", name: "D?ng b? Phu?ng Long Bi�n" },
  { code: "DV031", name: "D?ng b? Phu?ng Nghia D�" },
  { code: "DV032", name: "D?ng b? Phu?ng Ng?c H�" },
  { code: "DV033", name: "D?ng b? Phu?ng � Ch? D?a" },
  { code: "DV034", name: "D?ng b? Phu?ng Ph� Di?n" },
  { code: "DV035", name: "D?ng b? Phu?ng Ph� Luong" },
  { code: "DV036", name: "D?ng b? Phu?ng Ph� Thu?ng" },
  { code: "DV037", name: "D?ng b? Phu?ng Ph�c L?i" },
  { code: "DV038", name: "D?ng b? Phu?ng Phuong Li?t" },
  { code: "DV039", name: "D?ng b? Phu?ng Son T�y" },
  { code: "DV040", name: "D?ng b? Phu?ng T�y H?" },
  { code: "DV041", name: "D?ng b? Phu?ng T�y M?" },
  { code: "DV042", name: "D?ng b? Phu?ng T�y T?u" },
  { code: "DV043", name: "D?ng b? Phu?ng T�ng Thi?n" },
  { code: "DV044", name: "D?ng b? Phu?ng T? Li�m" },
  { code: "DV045", name: "D?ng b? Phu?ng Tuong Mai" },
  { code: "DV046", name: "D?ng b? Phu?ng Thanh Li?t" },
  { code: "DV047", name: "D?ng b? Phu?ng Thanh Xu�n" },
  { code: "DV048", name: "D?ng b? Phu?ng Thu?ng C�t" },
  { code: "DV049", name: "D?ng b? Phu?ng Van Mi?u-QTG" },
  { code: "DV050", name: "D?ng b? Phu?ng Vi?t Hung" },
  { code: "DV051", name: "D?ng b? Phu?ng Vinh Hung" },
  { code: "DV052", name: "D?ng b? Phu?ng Vinh Tuy" },
  { code: "DV053", name: "D?ng b? Phu?ng Xu�n D?nh" },
  { code: "DV054", name: "D?ng b? Phu?ng Xu�n Phuong" },
  { code: "DV055", name: "D?ng b? Phu?ng Y�n Ho�" },
  { code: "DV056", name: "D?ng b? Phu?ng Y�n Nghia" },
  { code: "DV057", name: "D?ng b? Phu?ng Y�n S?" },
  { code: "DV058", name: "D?ng b? X� An Kh�nh" },
  { code: "DV059", name: "D?ng b? X� Ba V�" },
  { code: "DV060", name: "D?ng b? X� B�t Tr�ng" },
  { code: "DV061", name: "D?ng b? X� B?t B?t" },
  { code: "DV062", name: "D?ng b? X� B�nh Minh" },
  { code: "DV063", name: "D?ng b? X� C? D�" },
  { code: "DV064", name: "D?ng b? X� Chuy�n M?" },
  { code: "DV065", name: "D?ng b? X� Chuong Duong" },
  { code: "DV066", name: "D?ng b? X� D�n Ho�" },
  { code: "DV067", name: "D?ng b? X� Duong H�a" },
  { code: "DV068", name: "D?ng b? X� Da Ph�c" },
  { code: "DV069", name: "D?ng b? X� D?i Th�nh" },
  { code: "DV070", name: "D?ng b? X� D?i Xuy�n" },
  { code: "DV071", name: "D?ng b? X� Dan Phu?ng" },
  { code: "DV072", name: "D?ng b? x� Do�i Phuong" },
  { code: "DV073", name: "D?ng b? X� D�ng Anh" },
  { code: "DV074", name: "D?ng b? X� Gia L�m" },
  { code: "DV075", name: "D?ng b? X� H? B?ng" },
  { code: "DV076", name: "D?ng b? X� H�t M�n" },
  { code: "DV077", name: "D?ng b? X� Ho� L?c" },
  { code: "DV078", name: "D?ng b? X� Ho� Ph�" },
  { code: "DV079", name: "D?ng b? X� Ho� X�" },
  { code: "DV080", name: "D?ng b? X� Ho�i D?c" },
  { code: "DV081", name: "D?ng b? X� H?ng Son" },
  { code: "DV082", name: "D?ng b? X� H?ng V�n" },
  { code: "DV083", name: "D?ng b? X� H�ng D?o" },
  { code: "DV084", name: "D?ng b? X� Huong Son" },
  { code: "DV085", name: "D?ng b? X� Ki?u Ph�" },
  { code: "DV086", name: "D?ng b? X� Kim Anh" },
  { code: "DV087", name: "D?ng b? X� Li�n Minh" },
  { code: "DV088", name: "D?ng b? X� M� Linh" },
  { code: "DV089", name: "D?ng b? X� Minh Ch�u" },
  { code: "DV090", name: "D?ng b? X� M? D?c" },
  { code: "DV091", name: "D?ng b? X� Nam Ph�" },
  { code: "DV092", name: "D?ng b? X� N?i B�i" },
  { code: "DV093", name: "D?ng b? X� Ng?c H?i" },
  { code: "DV094", name: "D?ng b? X� � Di�n" },
  { code: "DV095", name: "D?ng b? X� Ph� C�t" },
  { code: "DV096", name: "D?ng b? X� Ph� D�ng" },
  { code: "DV097", name: "D?ng b? X� Ph� Nghia" },
  { code: "DV098", name: "D?ng b? X� Ph� Xuy�n" },
  { code: "DV099", name: "D?ng b? X� Ph�c L?c" },
  { code: "DV100", name: "D?ng b? X� Ph�c Son" },
  { code: "DV101", name: "D?ng b? X� Ph�c Th?nh" },
  { code: "DV102", name: "D?ng b? X� Ph�c Th?" },
  { code: "DV103", name: "D?ng b? X� Phu?ng D?c" },
  { code: "DV104", name: "D?ng b? X� Qu?ng B?" },
  { code: "DV105", name: "D?ng b? X� Quang Minh" },
  { code: "DV106", name: "D?ng b? X� Qu?ng Oai" },
  { code: "DV107", name: "D?ng b? X� Qu?c Oai" },
  { code: "DV108", name: "D?ng b? X� S�c Son" },
  { code: "DV109", name: "D?ng b? X� Son D�ng" },
  { code: "DV110", name: "D?ng b? X� Su?i Hai" },
  { code: "DV111", name: "D?ng b? X� Tam Hung" },
  { code: "DV112", name: "D?ng b? X� T�y Phuong" },
  { code: "DV113", name: "D?ng b? X� Ti?n Th?ng" },
  { code: "DV114", name: "D?ng b? X� Th?ch Th?t" },
  { code: "DV115", name: "D?ng b? X� Thanh Oai" },
  { code: "DV116", name: "D?ng b? X� Thanh Tr�" },
  { code: "DV117", name: "D?ng b? X� Thi�n L?c" },
  { code: "DV118", name: "D?ng b? X� Thu?n An" },
  { code: "DV119", name: "D?ng b? X� Th?y L�m" },
  { code: "DV120", name: "D?ng b? X� Thu?ng Ph�c" },
  { code: "DV121", name: "D?ng b? X� Thu?ng T�n" },
  { code: "DV122", name: "D?ng b? X� Tr?n Ph�" },
  { code: "DV123", name: "D?ng b? X� Trung Gi�" },
  { code: "DV124", name: "D?ng b? X� ?ng Ho�" },
  { code: "DV125", name: "D?ng b? X� ?ng Thi�n" },
  { code: "DV126", name: "D?ng b? X� V�n D�nh" },
  { code: "DV127", name: "D?ng b? X� V?t L?i" },
  { code: "DV128", name: "D?ng b? X� Vinh Thanh" },
  { code: "DV129", name: "D?ng b? X� Xu�n Mai" },
  { code: "DV130", name: "D?ng b? X� Y�n B�i" },
  { code: "DV131", name: "D?ng b? X� Y�n L�ng" },
  { code: "DV132", name: "D?ng b? X� Y�n Xu�n" },
];

export const YEARS = ["2024", "2025", "2026", "2027", "2028"];

