import { SheetConfig, Unit } from './types';

export const SHEET_CONFIGS: SheetConfig[] = [
  { name: "1B", startRow: 9, endRow: 23, startCol: 2, endCol: 7 },
  { name: "1C", startRow: 10, endRow: 58, startCol: 2, endCol: 12 },
  { name: "1D", startRow: 8, endRow: 12, startCol: 2, endCol: 3 },
  { name: "2B", startRow: 7, endRow: 10, startCol: 3, endCol: 11 },
  { name: "2C", startRow: 7, endRow: 10, startCol: 2, endCol: 7 },
  { name: "3", startRow: 10, endRow: 24, startCol: 2, endCol: 7 },
  { name: "4B", startRow: 8, endRow: 22, startCol: 2, endCol: 4 },
  { name: "4C", startRow: 7, endRow: 21, startCol: 2, endCol: 7 },
  { name: "5A", startRow: 9, endRow: 46, startCol: 3, endCol: 15 },
  { name: "5B", startRow: 7, endRow: 20, startCol: 2, endCol: 3 },
  { name: "6", startRow: 9, endRow: 23, startCol: 2, endCol: 13 },
  { name: "7", startRow: 8, endRow: 35, startCol: 2, endCol: 5 },
];

export const SHEET_LABELS: { [key: string]: { label: string; row: number }[] } = {
  "1B": [
    { row: 9, label: "1. Xã, phường, thị trấn *" },
    { row: 10, label: "2. Thôn, tổ dân phố" },
    { row: 11, label: "3. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 12, label: "4. Cơ quan Nhà nước" },
    { row: 13, label: "5. Đơn vị sự nghiệp" },
    { row: 14, label: "a) Công lập" },
    { row: 15, label: "b) Ngoài công lập" },
    { row: 16, label: "6. Quân đội" },
    { row: 17, label: "7. Công an" },
    { row: 18, label: "8. Doanh nghiệp và hợp tác xã" },
    { row: 19, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 20, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 21, label: "c) Hợp tác xã" },
    { row: 22, label: "9. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 23, label: "10. Loại hình tổ chức cơ sở đảng khác" },
  ],
  "1C": [
    { row: 10, label: "1. Xã, phường, thị trấn" },
    { row: 11, label: "2. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 12, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 13, label: "3. Cơ quan Nhà nước" },
    { row: 14, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 15, label: "4. Đơn vị sự nghiệp (4=a+b)" },
    { row: 16, label: "a) Công lập" },
    { row: 17, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 18, label: "b) Ngoài công lập" },
    { row: 19, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 20, label: "5. Quân đội" },
    { row: 21, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 22, label: "6. Công an" },
    { row: 23, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 24, label: "7. Doanh nghiệp và hợp tác xã (7=a+b+c)" },
    { row: 25, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 26, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 27, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 28, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 29, label: "c) Hợp tác xã" },
    { row: 30, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 31, label: "8. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 32, label: "9. Loại hình tổ chức cơ sở đảng khác (Ghi cụ thể loại hình cơ sở khác)" },
    { row: 33, label: "Cộng (1+....+9)" },
    { row: 34, label: "Tính đến 01/3/2026" },
    { row: 35, label: "1. Thôn, tổ dân phố" },
    { row: 36, label: "2. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 37, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 38, label: "3. Cơ quan Nhà nước" },
    { row: 39, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 40, label: "4. Đơn vị sự nghiệp (4=a+b)" },
    { row: 41, label: "a) Công lập" },
    { row: 42, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 43, label: "b) Ngoài công lập" },
    { row: 44, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 45, label: "5. Quân đội" },
    { row: 46, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 47, label: "6. Công an" },
    { row: 48, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 49, label: "7. Doanh nghiệp và hợp tác xã (7=a+b+c)" },
    { row: 50, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 51, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 52, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 53, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 54, label: "c) Hợp tác xã" },
    { row: 55, label: "Trong đó: trực thuộc đảng ủy cấp xã" },
    { row: 56, label: "8. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 57, label: "9. Loại hình tổ chức cơ sở đảng khác (Ghi cụ thể loại hình cơ sở khác)" },
    { row: 58, label: "Cộng (1+....+9)" },
  ],
  "1D": [
    { row: 8, label: "1. Chi bộ có từ 30 đảng viên đến dưới 50 đảng viên" },
    { row: 9, label: "2. Chi bộ có từ 50 đảng viên đến dưới 100 đảng viên" },
    { row: 10, label: "3. Chi bộ có từ 100 đảng viên đến dưới 200 đảng viên" },
    { row: 11, label: "4. Chi bộ có từ 200 đảng viên trở lên" },
    { row: 12, label: "Tổng số" },
  ],
  "2B": [
    { row: 7, label: "1. Số xã" },
    { row: 8, label: "2. Số thôn, bản, ấp" },
    { row: 9, label: "3. Số thôn, bản, ấp chưa có chi bộ" },
    { row: 10, label: "4. Số thôn, bản, ấp chưa có đảng viên" },
  ],
  "2C": [
    { row: 7, label: "1. Tổ chức đảng ở đặc khu" },
    { row: 8, label: "2. Tổ chức đảng ở khu vực miền núi, vùng sâu, vùng xa" },
    { row: 9, label: "3. Tổ chức đảng ở các tổ chức, cơ quan, đơn vị có trụ sở chi nhánh..." },
    { row: 10, label: "4. Tổ chức đảng có đảng viên phải thực hiện nhiệm vụ đặc thù" },
  ],
  "3": [
    { row: 10, label: "--- TÍNH ĐẾN 01/3/2026 ---" },
    { row: 11, label: "1. Thôn, tổ dân phố" },
    { row: 12, label: "2. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 13, label: "3. Cơ quan Nhà nước" },
    { row: 14, label: "4. Đơn vị sự nghiệp (4=a+b)" },
    { row: 15, label: "a) Công lập" },
    { row: 16, label: "b) Ngoài công lập" },
    { row: 17, label: "5. Quân đội" },
    { row: 18, label: "6. Công an" },
    { row: 19, label: "7. Doanh nghiệp và hợp tác xã (7=a+b+c)" },
    { row: 20, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 21, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 22, label: "c) Hợp tác xã" },
    { row: 23, label: "8. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 24, label: "9. Loại hình tổ chức cơ sở đảng khác" },
  ],
  "4B": [
    { row: 8, label: "I. Tính chất đặc thù" },
    { row: 9, label: "1. Có đảng viên sinh sống, công tác, lao động phân tán, gồm:" },
    { row: 10, label: "- Ở nước ngoài" },
    { row: 11, label: "- Ở nhiều tỉnh, thành phố trực thuộc Trung ương" },
    { row: 12, label: "- Có đảng viên sinh sống, công tác không thường xuyên" },
    { row: 13, label: "- Có đảng viên đi làm ăn xa" },
    { row: 14, label: "- Có đảng viên là sinh viên trong thời gian nghỉ hè" },
    { row: 15, label: "2. Đảng viên thực hiện nhiệm vụ không thể rời vị trí, gồm:" },
    { row: 16, label: "- Đơn vị lực lượng vũ trang" },
    { row: 17, label: "- Đơn vị y tế" },
    { row: 18, label: "- Đơn vị kiểm lâm" },
    { row: 19, label: "- Có đảng viên là thuyền viên tàu tuyến quốc tế" },
    { row: 20, label: "- Có đảng viên làm việc ở công trình biển, hải đảo" },
    { row: 21, label: "II. Hoàn cảnh đặc biệt" },
    { row: 22, label: "- Ở nơi bị thiên tai, địa bàn bị cô lập, kéo dài" },
  ],
  "4C": [
    { row: 7, label: "1. Thôn, tổ dân phố" },
    { row: 8, label: "2. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 9, label: "3. Cơ quan Nhà nước" },
    { row: 10, label: "4. Đơn vị sự nghiệp" },
    { row: 11, label: "a) Công lập" },
    { row: 12, label: "b) Ngoài công lập" },
    { row: 13, label: "5. Quân đội" },
    { row: 14, label: "6. Công an" },
    { row: 15, label: "7. Doanh nghiệp và hợp tác xã" },
    { row: 16, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 17, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 18, label: "c) Hợp tác xã" },
    { row: 19, label: "8. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 20, label: "9. Loại hình tổ chức cơ sở đảng khác" },
    { row: 21, label: "Cộng" },
  ],
  "5A": [
    { row: 9, label: "1. Cấp ủy cơ sở" },
    { row: 10, label: "1.1 Dân tộc thiểu số" },
    { row: 11, label: "1.2 Tôn giáo" },
    { row: 12, label: "1.3 Nữ" },
    { row: 13, label: "1.4 Tuổi đời" },
    { row: 14, label: "- Dưới 40 tuổi" },
    { row: 15, label: "- Từ 41 đến 45 tuổi" },
    { row: 16, label: "- Từ 46 đến 50 tuổi" },
    { row: 17, label: "- Từ 51 đến 55 tuổi" },
    { row: 18, label: "- Trên 55 tuổi" },
    { row: 19, label: "1.5 Trình độ chuyên môn" },
    { row: 20, label: "- Sau đại học" },
    { row: 21, label: "- Đại học, cao đẳng" },
    { row: 22, label: "- Trung cấp" },
    { row: 23, label: "- Sơ cấp, Chưa qua đào tạo" },
    { row: 24, label: "1.6 Trình độ lý luận chính trị" },
    { row: 25, label: "- Cao cấp, cử nhân" },
    { row: 26, label: "- Trung cấp" },
    { row: 27, label: "- Sơ cấp, Chưa qua đào tạo" },
    { row: 28, label: "2. Bí thư cấp ủy cơ sở" },
    { row: 29, label: "2.1 Dân tộc thiểu số" },
    { row: 30, label: "2.2 Tôn giáo" },
    { row: 31, label: "2.3 Nữ" },
    { row: 32, label: "2.4 Tuổi đời" },
    { row: 33, label: "- Dưới 40 tuổi" },
    { row: 34, label: "- Từ 41 đến 45 tuổi" },
    { row: 35, label: "- Từ 46 đến 50 tuổi" },
    { row: 36, label: "- Từ 51 đến 55 tuổi" },
    { row: 37, label: "- Trên 55 tuổi" },
    { row: 38, label: "2.5 Trình độ chuyên môn" },
    { row: 39, label: "- Sau đại học" },
    { row: 40, label: "- Đại học, cao đẳng" },
    { row: 41, label: "- Trung cấp" },
    { row: 42, label: "- Sơ cấp, Chưa qua đào tạo" },
    { row: 43, label: "2.6 Trình độ lý luận chính trị" },
    { row: 44, label: "- Cao cấp, cử nhân" },
    { row: 45, label: "- Trung cấp" },
    { row: 46, label: "- Sơ cấp, Chưa qua đào tạo" },
  ],
  "5B": [
    { row: 7, label: "1. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 8, label: "2. Cơ quan Nhà nước" },
    { row: 9, label: "3. Đơn vị sự nghiệp" },
    { row: 10, label: "a) Công lập" },
    { row: 11, label: "b) Ngoài công lập" },
    { row: 12, label: "4. Quân đội" },
    { row: 13, label: "5. Công an" },
    { row: 14, label: "6. Doanh nghiệp và hợp tác xã" },
    { row: 15, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 16, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 17, label: "c) Hợp tác xã" },
    { row: 18, label: "7. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 19, label: "8. Loại hình tổ chức cơ sở đảng khác" },
    { row: 20, label: "Cộng" },
  ],
  "6": [
    { row: 9, label: "--- TỪ 1/7/2025 ĐẾN 01/3/2026 ---" },
    { row: 10, label: "1. Thôn, tổ dân phố" },
    { row: 11, label: "2. Cơ quan đảng, MTTQ, tổ chức CT-XH" },
    { row: 12, label: "3. Cơ quan Nhà nước" },
    { row: 13, label: "4. Đơn vị sự nghiệp" },
    { row: 14, label: "a) Công lập" },
    { row: 15, label: "b) Ngoài công lập" },
    { row: 16, label: "5. Quân đội" },
    { row: 17, label: "6. Công an" },
    { row: 18, label: "7. Doanh nghiệp và hợp tác xã" },
    { row: 19, label: "a) Doanh nghiệp có vốn Nhà nước" },
    { row: 20, label: "b) Doanh nghiệp ngoài khu vực Nhà nước" },
    { row: 21, label: "c) Hợp tác xã" },
    { row: 22, label: "8. Tổ chức cơ sở đảng ở ngoài nước" },
    { row: 23, label: "9. Loại hình tổ chức cơ sở đảng khác" },
  ],
  "7": [
    { row: 8, label: "IV. Xóa tên, trong đó:" },
    { row: 9, label: "- Đảng viên bỏ sinh hoạt đảng hoặc không đóng đảng phí" },
    { row: 10, label: "- Đảng viên tự ý trả thẻ hoặc tự hủy thẻ" },
    { row: 11, label: "- Đảng viên giảm sút ý chí phấn đấu" },
    { row: 12, label: "- Đảng viên hai năm liền vi phạm tư cách" },
    { row: 13, label: "- Đảng viên không bảo đảm tiêu chuẩn chính trị" },
    { row: 14, label: "V. Xin ra khỏi Đảng, trong đó:" },
    { row: 15, label: "- Cán bộ, công chức" },
    { row: 16, label: "- Học sinh" },
    { row: 17, label: "- Sinh viên" },
    { row: 18, label: "- Bộ đội xuất ngũ" },
    { row: 19, label: "- Đối tượng khác" },
    { row: 20, label: "VI. Tổng số đảng viên được miễn công tác và sinh hoạt" },
    { row: 21, label: "1. Do tuổi cao, sức yếu" },
    { row: 22, label: "2. Không vì lý do tuổi cao, sức yếu, trong đó:" },
    { row: 23, label: "- Điều trị bệnh dài ngày hoặc ở xa nơi cư trú" },
    { row: 24, label: "- Ra nước ngoài làm nhiệm vụ đơn lẻ, du lịch..." },
    { row: 25, label: "- Đi lao động đơn lẻ, vùng xa, không có tổ chức đảng" },
    { row: 26, label: "- Đi làm việc lưu động trong nước dưới 1 năm" },
    { row: 27, label: "- Nghỉ công tác chờ hưu" },
    { row: 28, label: "- Đảng viên nữ trong thời gian sinh con" },
    { row: 29, label: "- Trường hợp khác" },
    { row: 30, label: "VII. Tổng số đảng viên đi làm ăn xa nơi cư trú" },
    { row: 31, label: "1. Chưa được xét miễn công tác và sinh hoạt" },
    { row: 32, label: "2. Đã được xét miễn công tác và sinh hoạt, trong đó:" },
    { row: 33, label: "- Miễn 1 lần" },
    { row: 34, label: "- Miễn 2 lần" },
    { row: 35, label: "- Miễn 3 lần trở lên" },
  ],
};

export const SHEET_COLUMN_HEADERS: { [key: string]: string[] } = {
  "1B": [
    "Số TCCSĐ (đến 01/7/2025)",
    "Thành lập mới",
    "Giải thể",
    "Theo dõi (Tổng số)",
    "Đã củng cố xong",
    "Số TCCSĐ (đến 31/3/2026)"
  ],
  "1C": [
    "Tổng số (CB cơ sở)",
    "CB có 3-5 ĐV",
    "CB có 6-9 ĐV",
    "CB có >=10 ĐV",
    "Tổng số (CB trực thuộc)",
    "CB có 3-5 ĐV",
    "CB có 6-9 ĐV",
    "CB có 10-30 ĐV",
    "CB có 30-100 ĐV",
    "CB có >100 ĐV",
    "Tự động"
  ],
  "1D": ["Tổng số", "Thành lập tự động"],
  "2B": [
    "2022-KV I", "2022-KV II", "2022-KV III",
    "30/6/25-KV I", "30/6/25-KV II", "30/6/25-KV III",
    "01/3/26-KV I", "01/3/26-KV II", "01/3/26-KV III"
  ],
  "2C": [
    "Trước 30/3/25-ĐBCS", "Trước 30/3/25-CBCS", "Trước 30/3/25-CBTT",
    "Đến 01/3/26-ĐBCS", "Đến 01/3/26-CBCS", "Đến 01/3/26-CBTT"
  ],
  "3": [
    "Triển khai-Tổng", "Triển khai-CB", "Triển khai-ĐB",
    "Công nhận-Tổng", "Công nhận-CB", "Công nhận-ĐB"
  ],
  "4B": ["Đảng bộ cơ sở", "Chi bộ cơ sở", "Chi bộ trực thuộc"],
  "4C": [
    "Số CB thực hiện", "Lý do: 50-100 ĐV", "Lý do: 100-200 ĐV",
    "Lý do: >200 ĐV", "Lý do: Địa điểm", "Lý do khác"
  ],
  "5A": [
    "Tổng số", "Thôn/Tổ dân phố", "Cơ quan Đảng/MTTQ", "Cơ quan Nhà nước",
    "Sự nghiệp công", "Sự nghiệp tư", "Quân đội", "Công an",
    "DN Nhà nước", "DN tư nhân", "HTX", "Ngoài nước", "Khác"
  ],
  "5B": ["Đến 01/7/2026", "Đến 31/3/2026"],
  "6": [
    "Sau ĐH", "ĐH/CĐ", "Trung cấp", "Cử nhân/CC", "Trung cấp LL",
    "NV Xây dựng Đảng", "NV Đoàn thể", "QL Nhà nước", "Ngoại ngữ", "Tin học",
    "Bồi dưỡng kỹ năng", "QP-AN"
  ],
  "7": [
    "31/12/22-Tổng ĐV", "31/12/22-Mới",
    "01/3/26-Tổng ĐV", "01/3/26-Mới"
  ],
};

export const UNITS: Unit[] = [
  { code: "TOTAL_HN", name: "Äáº£ng bá»™ ThÃ nh phá»‘ HÃ  Ná»™i (Tá»•NG Há»£P)" },
  { code: "DV001", name: "Đảng bộ các cơ quan Đảng Thành phố" },
  { code: "DV002", name: "Đảng bộ UBND Thành phố" },
  { code: "DV003", name: "Đảng bộ Công an Thành phố" },
  { code: "DV004", name: "Đảng bộ Bộ Tư lệnh Thủ đô" },
  { code: "DV005", name: "Đảng bộ các Trường Đại học, Cao đẳng" },
  { code: "DV006", name: "Đảng bộ Đại học Quốc gia Hà Nội" },
  { code: "DV007", name: "Đảng bộ Phường Ba Đình" },
  { code: "DV008", name: "Đảng bộ Phường Bạch Mai" },
  { code: "DV009", name: "Đảng bộ Phường Bồ Đề" },
  { code: "DV010", name: "Đảng bộ Phường Cầu Giấy" },
  { code: "DV011", name: "Đảng bộ Phường Cửa Nam" },
  { code: "DV012", name: "Đảng bộ Phường Chương Mỹ" },
  { code: "DV013", name: "Đảng bộ Phường Dương Nội" },
  { code: "DV014", name: "Đảng bộ Phường Đại Mỗ" },
  { code: "DV015", name: "Đảng bộ Phường Định Công" },
  { code: "DV016", name: "Đảng bộ Phường Đống Đa" },
  { code: "DV017", name: "Đảng bộ Phường Đông Ngạc" },
  { code: "DV018", name: "Đảng bộ Phường Giảng Võ" },
  { code: "DV019", name: "Đảng bộ Phường Hà Đông" },
  { code: "DV020", name: "Đảng bộ Phường Hai Bà Trưng" },
  { code: "DV021", name: "Đảng bộ Phường Hoàn Kiếm" },
  { code: "DV022", name: "Đảng bộ Phường Hoàng Liệt" },
  { code: "DV023", name: "Đảng bộ Phường Hoàng Mai" },
  { code: "DV024", name: "Đảng bộ Phường Hồng Hà" },
  { code: "DV025", name: "Đảng bộ Phường Kiến Hưng" },
  { code: "DV026", name: "Đảng bộ Phường Kim Liên" },
  { code: "DV027", name: "Đảng bộ Phường Khương Đình" },
  { code: "DV028", name: "Đảng bộ Phường Láng" },
  { code: "DV029", name: "Đảng bộ Phường Lĩnh Nam" },
  { code: "DV030", name: "Đảng bộ Phường Long Biên" },
  { code: "DV031", name: "Đảng bộ Phường Nghĩa Đô" },
  { code: "DV032", name: "Đảng bộ Phường Ngọc Hà" },
  { code: "DV033", name: "Đảng bộ Phường Ô Chợ Dừa" },
  { code: "DV034", name: "Đảng bộ Phường Phú Diễn" },
  { code: "DV035", name: "Đảng bộ Phường Phú Lương" },
  { code: "DV036", name: "Đảng bộ Phường Phú Thượng" },
  { code: "DV037", name: "Đảng bộ Phường Phúc Lợi" },
  { code: "DV038", name: "Đảng bộ Phường Phương Liệt" },
  { code: "DV039", name: "Đảng bộ Phường Sơn Tây" },
  { code: "DV040", name: "Đảng bộ Phường Tây Hồ" },
  { code: "DV041", name: "Đảng bộ Phường Tây Mỗ" },
  { code: "DV042", name: "Đảng bộ Phường Tây Tựu" },
  { code: "DV043", name: "Đảng bộ Phường Tùng Thiện" },
  { code: "DV044", name: "Đảng bộ Phường Từ Liêm" },
  { code: "DV045", name: "Đảng bộ Phường Tương Mai" },
  { code: "DV046", name: "Đảng bộ Phường Thanh Liệt" },
  { code: "DV047", name: "Đảng bộ Phường Thanh Xuân" },
  { code: "DV048", name: "Đảng bộ Phường Thượng Cát" },
  { code: "DV049", name: "Đảng bộ Phường Văn Miếu-QTG" },
  { code: "DV050", name: "Đảng bộ Phường Việt Hưng" },
  { code: "DV051", name: "Đảng bộ Phường Vĩnh Hưng" },
  { code: "DV052", name: "Đảng bộ Phường Vĩnh Tuy" },
  { code: "DV053", name: "Đảng bộ Phường Xuân Đỉnh" },
  { code: "DV054", name: "Đảng bộ Phường Xuân Phương" },
  { code: "DV055", name: "Đảng bộ Phường Yên Hoà" },
  { code: "DV056", name: "Đảng bộ Phường Yên Nghĩa" },
  { code: "DV057", name: "Đảng bộ Phường Yên Sở" },
  { code: "DV058", name: "Đảng bộ Xã An Khánh" },
  { code: "DV059", name: "Đảng bộ Xã Ba Vì" },
  { code: "DV060", name: "Đảng bộ Xã Bát Tràng" },
  { code: "DV061", name: "Đảng bộ Xã Bất Bạt" },
  { code: "DV062", name: "Đảng bộ Xã Bình Minh" },
  { code: "DV063", name: "Đảng bộ Xã Cổ Đô" },
  { code: "DV064", name: "Đảng bộ Xã Chuyên Mỹ" },
  { code: "DV065", name: "Đảng bộ Xã Chương Dương" },
  { code: "DV066", name: "Đảng bộ Xã Dân Hoà" },
  { code: "DV067", name: "Đảng bộ Xã Dương Hòa" },
  { code: "DV068", name: "Đảng bộ Xã Đa Phúc" },
  { code: "DV069", name: "Đảng bộ Xã Đại Thanh" },
  { code: "DV070", name: "Đảng bộ Xã Đại Xuyên" },
  { code: "DV071", name: "Đảng bộ Xã Đan Phượng" },
  { code: "DV072", name: "Đảng bộ xã Đoài Phương" },
  { code: "DV073", name: "Đảng bộ Xã Đông Anh" },
  { code: "DV074", name: "Đảng bộ Xã Gia Lâm" },
  { code: "DV075", name: "Đảng bộ Xã Hạ Bằng" },
  { code: "DV076", name: "Đảng bộ Xã Hát Môn" },
  { code: "DV077", name: "Đảng bộ Xã Hoà Lạc" },
  { code: "DV078", name: "Đảng bộ Xã Hoà Phú" },
  { code: "DV079", name: "Đảng bộ Xã Hoà Xá" },
  { code: "DV080", name: "Đảng bộ Xã Hoài Đức" },
  { code: "DV081", name: "Đảng bộ Xã Hồng Sơn" },
  { code: "DV082", name: "Đảng bộ Xã Hồng Vân" },
  { code: "DV083", name: "Đảng bộ Xã Hưng Đạo" },
  { code: "DV084", name: "Đảng bộ Xã Hương Sơn" },
  { code: "DV085", name: "Đảng bộ Xã Kiều Phú" },
  { code: "DV086", name: "Đảng bộ Xã Kim Anh" },
  { code: "DV087", name: "Đảng bộ Xã Liên Minh" },
  { code: "DV088", name: "Đảng bộ Xã Mê Linh" },
  { code: "DV089", name: "Đảng bộ Xã Minh Châu" },
  { code: "DV090", name: "Đảng bộ Xã Mỹ Đức" },
  { code: "DV091", name: "Đảng bộ Xã Nam Phù" },
  { code: "DV092", name: "Đảng bộ Xã Nội Bài" },
  { code: "DV093", name: "Đảng bộ Xã Ngọc Hồi" },
  { code: "DV094", name: "Đảng bộ Xã Ô Diên" },
  { code: "DV095", name: "Đảng bộ Xã Phú Cát" },
  { code: "DV096", name: "Đảng bộ Xã Phù Đổng" },
  { code: "DV097", name: "Đảng bộ Xã Phú Nghĩa" },
  { code: "DV098", name: "Đảng bộ Xã Phú Xuyên" },
  { code: "DV099", name: "Đảng bộ Xã Phúc Lộc" },
  { code: "DV100", name: "Đảng bộ Xã Phúc Sơn" },
  { code: "DV101", name: "Đảng bộ Xã Phúc Thịnh" },
  { code: "DV102", name: "Đảng bộ Xã Phúc Thọ" },
  { code: "DV103", name: "Đảng bộ Xã Phượng Dực" },
  { code: "DV104", name: "Đảng bộ Xã Quảng Bị" },
  { code: "DV105", name: "Đảng bộ Xã Quang Minh" },
  { code: "DV106", name: "Đảng bộ Xã Quảng Oai" },
  { code: "DV107", name: "Đảng bộ Xã Quốc Oai" },
  { code: "DV108", name: "Đảng bộ Xã Sóc Sơn" },
  { code: "DV109", name: "Đảng bộ Xã Sơn Đồng" },
  { code: "DV110", name: "Đảng bộ Xã Suối Hai" },
  { code: "DV111", name: "Đảng bộ Xã Tam Hưng" },
  { code: "DV112", name: "Đảng bộ Xã Tây Phương" },
  { code: "DV113", name: "Đảng bộ Xã Tiến Thắng" },
  { code: "DV114", name: "Đảng bộ Xã Thạch Thất" },
  { code: "DV115", name: "Đảng bộ Xã Thanh Oai" },
  { code: "DV116", name: "Đảng bộ Xã Thanh Trì" },
  { code: "DV117", name: "Đảng bộ Xã Thiên Lộc" },
  { code: "DV118", name: "Đảng bộ Xã Thuận An" },
  { code: "DV119", name: "Đảng bộ Xã Thư Lâm" },
  { code: "DV120", name: "Đảng bộ Xã Thượng Phúc" },
  { code: "DV121", name: "Đảng bộ Xã Thường Tín" },
  { code: "DV122", name: "Đảng bộ Xã Trần Phú" },
  { code: "DV123", name: "Đảng bộ Xã Trung Giã" },
  { code: "DV124", name: "Đảng bộ Xã Ứng Hoà" },
  { code: "DV125", name: "Đảng bộ Xã Ứng Thiên" },
  { code: "DV126", name: "Đảng bộ Xã Vân Đình" },
  { code: "DV127", name: "Đảng bộ Xã Vật Lại" },
  { code: "DV128", name: "Đảng bộ Xã Vĩnh Thanh" },
  { code: "DV129", name: "Đảng bộ Xã Xuân Mai" },
  { code: "DV130", name: "Đảng bộ Xã Yên Bài" },
  { code: "DV131", name: "Đảng bộ Xã Yên Lãng" },
  { code: "DV132", name: "Đảng bộ Xã Yên Xuân" },
];

export const YEARS = ["2024", "2025", "2026", "2027", "2028"];

export const DEFAULT_REPORTING_YEAR = "2026";

export const DEFAULT_PROJECT_ID = "proj_nq22";
export const DEFAULT_PROJECT_NAME = "Tổng hợp NQ22";
