import { SheetConfig, Unit } from './types';

export const SHEET_CONFIGS: SheetConfig[] = [
  { name: "1B", startRow: 9, endRow: 23, startCol: 2, endCol: 7 },
  { name: "1C", startRow: 10, endRow: 58, startCol: 2, endCol: 12 },
  { name: "1D", startRow: 8, endRow: 12, startCol: 2, endCol: 3 },
  { name: "2B", startRow: 7, endRow: 10, startCol: 3, endCol: 11 },
  { name: "2C", startRow: 7, endRow: 10, startCol: 2, endCol: 7 },
  { name: "3", startRow: 10, endRow: 24, startCol: 2, endCol: 7 },
  { name: "4B", startRow: 8, endRow: 22, startCol: 2, endCol: 4 },
  { name: "4C", startRow: 7, endRow: 21, startCol: 2, endCol: 7 },
  { name: "5A", startRow: 9, endRow: 46, startCol: 3, endCol: 15 },
  { name: "5B", startRow: 7, endRow: 20, startCol: 2, endCol: 3 },
  { name: "6", startRow: 9, endRow: 23, startCol: 2, endCol: 13 },
  { name: "7", startRow: 8, endRow: 35, startCol: 2, endCol: 5 },
];

export const SHEET_LABELS: { [key: string]: { label: string; row: number }[] } = {
  "1B": [
    { row: 9, label: "1. X�, phu?ng, th? tr?n *" },
    { row: 10, label: "2. Th�n, t? d�n ph?" },
    { row: 11, label: "3. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 12, label: "4. Co quan Nh� nu?c" },
    { row: 13, label: "5. Don v? s? nghi?p" },
    { row: 14, label: "a) C�ng l?p" },
    { row: 15, label: "b) Ngo�i c�ng l?p" },
    { row: 16, label: "6. Qu�n d?i" },
    { row: 17, label: "7. C�ng an" },
    { row: 18, label: "8. Doanh nghi?p v� h?p t�c x�" },
    { row: 19, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 20, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 21, label: "c) H?p t�c x�" },
    { row: 22, label: "9. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 23, label: "10. Lo?i h�nh t? ch?c co s? d?ng kh�c" },
  ],
  "1C": [
    { row: 10, label: "1. X�, phu?ng, th? tr?n" },
    { row: 11, label: "2. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 12, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 13, label: "3. Co quan Nh� nu?c" },
    { row: 14, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 15, label: "4. Don v? s? nghi?p (4=a+b)" },
    { row: 16, label: "a) C�ng l?p" },
    { row: 17, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 18, label: "b) Ngo�i c�ng l?p" },
    { row: 19, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 20, label: "5. Qu�n d?i" },
    { row: 21, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 22, label: "6. C�ng an" },
    { row: 23, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 24, label: "7. Doanh nghi?p v� h?p t�c x� (7=a+b+c)" },
    { row: 25, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 26, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 27, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 28, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 29, label: "c) H?p t�c x�" },
    { row: 30, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 31, label: "8. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 32, label: "9. Lo?i h�nh t? ch?c co s? d?ng kh�c (Ghi c? th? lo?i h�nh co s? kh�c)" },
    { row: 33, label: "C?ng (1+....+9)" },
    { row: 34, label: "T�nh d?n 01/3/2026" },
    { row: 35, label: "1. Th�n, t? d�n ph?" },
    { row: 36, label: "2. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 37, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 38, label: "3. Co quan Nh� nu?c" },
    { row: 39, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 40, label: "4. Don v? s? nghi?p (4=a+b)" },
    { row: 41, label: "a) C�ng l?p" },
    { row: 42, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 43, label: "b) Ngo�i c�ng l?p" },
    { row: 44, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 45, label: "5. Qu�n d?i" },
    { row: 46, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 47, label: "6. C�ng an" },
    { row: 48, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 49, label: "7. Doanh nghi?p v� h?p t�c x� (7=a+b+c)" },
    { row: 50, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 51, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 52, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 53, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 54, label: "c) H?p t�c x�" },
    { row: 55, label: "Trong d�: tr?c thu?c d?ng ?y c?p x�" },
    { row: 56, label: "8. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 57, label: "9. Lo?i h�nh t? ch?c co s? d?ng kh�c (Ghi c? th? lo?i h�nh co s? kh�c)" },
    { row: 58, label: "C?ng (1+....+9)" },
  ],
  "1D": [
    { row: 8, label: "1. Chi b? c� t? 30 d?ng vi�n d?n du?i 50 d?ng vi�n" },
    { row: 9, label: "2. Chi b? c� t? 50 d?ng vi�n d?n du?i 100 d?ng vi�n" },
    { row: 10, label: "3. Chi b? c� t? 100 d?ng vi�n d?n du?i 200 d?ng vi�n" },
    { row: 11, label: "4. Chi b? c� t? 200 d?ng vi�n tr? l�n" },
    { row: 12, label: "T?ng s?" },
  ],
  "2B": [
    { row: 7, label: "1. S? x�" },
    { row: 8, label: "2. S? th�n, b?n, ?p" },
    { row: 9, label: "3. S? th�n, b?n, ?p chua c� chi b?" },
    { row: 10, label: "4. S? th�n, b?n, ?p chua c� d?ng vi�n" },
  ],
  "2C": [
    { row: 7, label: "1. T? ch?c d?ng ? d?c khu" },
    { row: 8, label: "2. T? ch?c d?ng ? khu v?c mi?n n�i, v�ng s�u, v�ng xa" },
    { row: 9, label: "3. T? ch?c d?ng ? c�c t? ch?c, co quan, don v? c� tr? s? chi nh�nh..." },
    { row: 10, label: "4. T? ch?c d?ng c� d?ng vi�n ph?i th?c hi?n nhi?m v? d?c th�" },
  ],
  "3": [
    { row: 10, label: "--- T�NH D?N 01/3/2026 ---" },
    { row: 11, label: "1. Th�n, t? d�n ph?" },
    { row: 12, label: "2. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 13, label: "3. Co quan Nh� nu?c" },
    { row: 14, label: "4. Don v? s? nghi?p (4=a+b)" },
    { row: 15, label: "a) C�ng l?p" },
    { row: 16, label: "b) Ngo�i c�ng l?p" },
    { row: 17, label: "5. Qu�n d?i" },
    { row: 18, label: "6. C�ng an" },
    { row: 19, label: "7. Doanh nghi?p v� h?p t�c x� (7=a+b+c)" },
    { row: 20, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 21, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 22, label: "c) H?p t�c x�" },
    { row: 23, label: "8. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 24, label: "9. Lo?i h�nh t? ch?c co s? d?ng kh�c" },
  ],
  "4B": [
    { row: 8, label: "I. T�nh ch?t d?c th�" },
    { row: 9, label: "1. C� d?ng vi�n sinh s?ng, c�ng t�c, lao d?ng ph�n t�n, g?m:" },
    { row: 10, label: "- ? nu?c ngo�i" },
    { row: 11, label: "- ? nhi?u t?nh, th�nh ph? tr?c thu?c Trung uong" },
    { row: 12, label: "- C� d?ng vi�n sinh s?ng, c�ng t�c kh�ng thu?ng xuy�n" },
    { row: 13, label: "- C� d?ng vi�n di l�m an xa" },
    { row: 14, label: "- C� d?ng vi�n l� sinh vi�n trong th?i gian ngh? h�" },
    { row: 15, label: "2. D?ng vi�n th?c hi?n nhi?m v? kh�ng th? r?i v? tr�, g?m:" },
    { row: 16, label: "- Don v? l?c lu?ng vu trang" },
    { row: 17, label: "- Don v? y t?" },
    { row: 18, label: "- Don v? ki?m l�m" },
    { row: 19, label: "- C� d?ng vi�n l� thuy?n vi�n t�u tuy?n qu?c t?" },
    { row: 20, label: "- C� d?ng vi�n l�m vi?c ? c�ng tr�nh bi?n, h?i d?o" },
    { row: 21, label: "II. Ho�n c?nh d?c bi?t" },
    { row: 22, label: "- ? noi b? thi�n tai, d?a b�n b? c� l?p, k�o d�i" },
  ],
  "4C": [
    { row: 7, label: "1. Th�n, t? d�n ph?" },
    { row: 8, label: "2. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 9, label: "3. Co quan Nh� nu?c" },
    { row: 10, label: "4. Don v? s? nghi?p" },
    { row: 11, label: "a) C�ng l?p" },
    { row: 12, label: "b) Ngo�i c�ng l?p" },
    { row: 13, label: "5. Qu�n d?i" },
    { row: 14, label: "6. C�ng an" },
    { row: 15, label: "7. Doanh nghi?p v� h?p t�c x�" },
    { row: 16, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 17, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 18, label: "c) H?p t�c x�" },
    { row: 19, label: "8. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 20, label: "9. Lo?i h�nh t? ch?c co s? d?ng kh�c" },
    { row: 21, label: "C?ng" },
  ],
  "5A": [
    { row: 9, label: "1. C?p ?y co s?" },
    { row: 10, label: "1.1 D�n t?c thi?u s?" },
    { row: 11, label: "1.2 T�n gi�o" },
    { row: 12, label: "1.3 N?" },
    { row: 13, label: "1.4 Tu?i d?i" },
    { row: 14, label: "- Du?i 40 tu?i" },
    { row: 15, label: "- T? 41 d?n 45 tu?i" },
    { row: 16, label: "- T? 46 d?n 50 tu?i" },
    { row: 17, label: "- T? 51 d?n 55 tu?i" },
    { row: 18, label: "- Tr�n 55 tu?i" },
    { row: 19, label: "1.5 Tr�nh d? chuy�n m�n" },
    { row: 20, label: "- Sau d?i h?c" },
    { row: 21, label: "- D?i h?c, cao d?ng" },
    { row: 22, label: "- Trung c?p" },
    { row: 23, label: "- So c?p, Chua qua d�o t?o" },
    { row: 24, label: "1.6 Tr�nh d? l� lu?n ch�nh tr?" },
    { row: 25, label: "- Cao c?p, c? nh�n" },
    { row: 26, label: "- Trung c?p" },
    { row: 27, label: "- So c?p, Chua qua d�o t?o" },
    { row: 28, label: "2. B� thu c?p ?y co s?" },
    { row: 29, label: "2.1 D�n t?c thi?u s?" },
    { row: 30, label: "2.2 T�n gi�o" },
    { row: 31, label: "2.3 N?" },
    { row: 32, label: "2.4 Tu?i d?i" },
    { row: 33, label: "- Du?i 40 tu?i" },
    { row: 34, label: "- T? 41 d?n 45 tu?i" },
    { row: 35, label: "- T? 46 d?n 50 tu?i" },
    { row: 36, label: "- T? 51 d?n 55 tu?i" },
    { row: 37, label: "- Tr�n 55 tu?i" },
    { row: 38, label: "2.5 Tr�nh d? chuy�n m�n" },
    { row: 39, label: "- Sau d?i h?c" },
    { row: 40, label: "- D?i h?c, cao d?ng" },
    { row: 41, label: "- Trung c?p" },
    { row: 42, label: "- So c?p, Chua qua d�o t?o" },
    { row: 43, label: "2.6 Tr�nh d? l� lu?n ch�nh tr?" },
    { row: 44, label: "- Cao c?p, c? nh�n" },
    { row: 45, label: "- Trung c?p" },
    { row: 46, label: "- So c?p, Chua qua d�o t?o" },
  ],
  "5B": [
    { row: 7, label: "1. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 8, label: "2. Co quan Nh� nu?c" },
    { row: 9, label: "3. Don v? s? nghi?p" },
    { row: 10, label: "a) C�ng l?p" },
    { row: 11, label: "b) Ngo�i c�ng l?p" },
    { row: 12, label: "4. Qu�n d?i" },
    { row: 13, label: "5. C�ng an" },
    { row: 14, label: "6. Doanh nghi?p v� h?p t�c x�" },
    { row: 15, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 16, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 17, label: "c) H?p t�c x�" },
    { row: 18, label: "7. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 19, label: "8. Lo?i h�nh t? ch?c co s? d?ng kh�c" },
    { row: 20, label: "C?ng" },
  ],
  "6": [
    { row: 9, label: "--- T? 1/7/2025 D?N 01/3/2026 ---" },
    { row: 10, label: "1. Th�n, t? d�n ph?" },
    { row: 11, label: "2. Co quan d?ng, MTTQ, t? ch?c CT-XH" },
    { row: 12, label: "3. Co quan Nh� nu?c" },
    { row: 13, label: "4. Don v? s? nghi?p" },
    { row: 14, label: "a) C�ng l?p" },
    { row: 15, label: "b) Ngo�i c�ng l?p" },
    { row: 16, label: "5. Qu�n d?i" },
    { row: 17, label: "6. C�ng an" },
    { row: 18, label: "7. Doanh nghi?p v� h?p t�c x�" },
    { row: 19, label: "a) Doanh nghi?p c� v?n Nh� nu?c" },
    { row: 20, label: "b) Doanh nghi?p ngo�i khu v?c Nh� nu?c" },
    { row: 21, label: "c) H?p t�c x�" },
    { row: 22, label: "8. T? ch?c co s? d?ng ? ngo�i nu?c" },
    { row: 23, label: "9. Lo?i h�nh t? ch?c co s? d?ng kh�c" },
  ],
  "7": [
    { row: 8, label: "IV. X�a t�n, trong d�:" },
    { row: 9, label: "- D?ng vi�n b? sinh ho?t d?ng ho?c kh�ng d�ng d?ng ph�" },
    { row: 10, label: "- D?ng vi�n t? � tr? th? ho?c t? h?y th?" },
    { row: 11, label: "- D?ng vi�n gi?m s�t � ch� ph?n d?u" },
    { row: 12, label: "- D?ng vi�n hai nam li?n vi ph?m tu c�ch" },
    { row: 13, label: "- D?ng vi�n kh�ng b?o d?m ti�u chu?n ch�nh tr?" },
    { row: 14, label: "V. Xin ra kh?i D?ng, trong d�:" },
    { row: 15, label: "- C�n b?, c�ng ch?c" },
    { row: 16, label: "- H?c sinh" },
    { row: 17, label: "- Sinh vi�n" },
    { row: 18, label: "- B? d?i xu?t ngu" },
    { row: 19, label: "- D?i tu?ng kh�c" },
    { row: 20, label: "VI. T?ng s? d?ng vi�n du?c mi?n c�ng t�c v� sinh ho?t" },
    { row: 21, label: "1. Do tu?i cao, s?c y?u" },
    { row: 22, label: "2. Kh�ng v� l� do tu?i cao, s?c y?u, trong d�:" },
    { row: 23, label: "- Di?u tr? b?nh d�i ng�y ho?c ? xa noi cu tr�" },
    { row: 24, label: "- Ra nu?c ngo�i l�m nhi?m v? don l?, du l?ch..." },
    { row: 25, label: "- Di lao d?ng don l?, v�ng xa, kh�ng c� t? ch?c d?ng" },
    { row: 26, label: "- Di l�m vi?c luu d?ng trong nu?c du?i 1 nam" },
    { row: 27, label: "- Ngh? c�ng t�c ch? huu" },
    { row: 28, label: "- D?ng vi�n n? trong th?i gian sinh con" },
    { row: 29, label: "- Tru?ng h?p kh�c" },
    { row: 30, label: "VII. T?ng s? d?ng vi�n di l�m an xa noi cu tr�" },
    { row: 31, label: "1. Chua du?c x�t mi?n c�ng t�c v� sinh ho?t" },
    { row: 32, label: "2. D� du?c x�t mi?n c�ng t�c v� sinh ho?t, trong d�:" },
    { row: 33, label: "- Mi?n 1 l?n" },
    { row: 34, label: "- Mi?n 2 l?n" },
    { row: 35, label: "- Mi?n 3 l?n tr? l�n" },
  ],
};

export const SHEET_COLUMN_HEADERS: { [key: string]: string[] } = {
  "1B": [
    "S? TCCSD (d?n 01/7/2025)",
    "Th�nh l?p m?i",
    "Gi?i th?",
    "Theo d�i (T?ng s?)",
    "D� c?ng c? xong",
    "S? TCCSD (d?n 31/3/2026)"
  ],
  "1C": [
    "T?ng s? (CB co s?)",
    "CB c� 3-5 DV",
    "CB c� 6-9 DV",
    "CB c� >=10 DV",
    "T?ng s? (CB tr?c thu?c)",
    "CB c� 3-5 DV",
    "CB c� 6-9 DV",
    "CB c� 10-30 DV",
    "CB c� 30-100 DV",
    "CB c� >100 DV",
    "T? d?ng"
  ],
  "1D": ["T?ng s?", "Th�nh l?p t? d?ng"],
  "2B": [
    "2022-KV I", "2022-KV II", "2022-KV III",
    "30/6/25-KV I", "30/6/25-KV II", "30/6/25-KV III",
    "01/3/26-KV I", "01/3/26-KV II", "01/3/26-KV III"
  ],
  "2C": [
    "Tru?c 30/3/25-DBCS", "Tru?c 30/3/25-CBCS", "Tru?c 30/3/25-CBTT",
    "D?n 01/3/26-DBCS", "D?n 01/3/26-CBCS", "D?n 01/3/26-CBTT"
  ],
  "3": [
    "Tri?n khai-T?ng", "Tri?n khai-CB", "Tri?n khai-DB",
    "C�ng nh?n-T?ng", "C�ng nh?n-CB", "C�ng nh?n-DB"
  ],
  "4B": ["D?ng b? co s?", "Chi b? co s?", "Chi b? tr?c thu?c"],
  "4C": [
    "S? CB th?c hi?n", "L� do: 50-100 DV", "L� do: 100-200 DV",
    "L� do: >200 DV", "L� do: D?a di?m", "L� do kh�c"
  ],
  "5A": [
    "T?ng s?", "Th�n/T? d�n ph?", "Co quan D?ng/MTTQ", "Co quan Nh� nu?c",
    "S? nghi?p c�ng", "S? nghi?p tu", "Qu�n d?i", "C�ng an",
    "DN Nh� nu?c", "DN tu nh�n", "HTX", "Ngo�i nu?c", "Kh�c"
  ],
  "5B": ["D?n 01/7/2026", "D?n 31/3/2026"],
  "6": [
    "Sau DH", "DH/CD", "Trung c?p", "C? nh�n/CC", "Trung c?p LL",
    "NV X�y d?ng D?ng", "NV Do�n th?", "QL Nh� nu?c", "Ngo?i ng?", "Tin h?c",
    "B?i du?ng k? nang", "QP-AN"
  ],
  "7": [
    "31/12/22-T?ng DV", "31/12/22-M?i",
    "01/3/26-T?ng DV", "01/3/26-M?i"
  ],
};

export const UNITS: Unit[] = [
  { code: "DV001", name: "D?ng b? c�c co quan D?ng Th�nh ph?" },
  { code: "DV002", name: "D?ng b? UBND Th�nh ph?" },
  { code: "DV003", name: "D?ng b? C�ng an Th�nh ph?" },
  { code: "DV004", name: "D?ng b? B? Tu l?nh Th? d�" },
  { code: "DV005", name: "D?ng b? c�c Tru?ng D?i h?c, Cao d?ng" },
  { code: "DV006", name: "D?ng b? D?i h?c Qu?c gia H� N?i" },
  { code: "DV007", name: "D?ng b? Phu?ng Ba D�nh" },
  { code: "DV008", name: "D?ng b? Phu?ng B?ch Mai" },
  { code: "DV009", name: "D?ng b? Phu?ng B? D?" },
  { code: "DV010", name: "D?ng b? Phu?ng C?u Gi?y" },
  { code: "DV011", name: "D?ng b? Phu?ng C?a Nam" },
  { code: "DV012", name: "D?ng b? Phu?ng Chuong M?" },
  { code: "DV013", name: "D?ng b? Phu?ng Duong N?i" },
  { code: "DV014", name: "D?ng b? Phu?ng D?i M?" },
  { code: "DV015", name: "D?ng b? Phu?ng D?nh C�ng" },
  { code: "DV016", name: "D?ng b? Phu?ng D?ng Da" },
  { code: "DV017", name: "D?ng b? Phu?ng D�ng Ng?c" },
  { code: "DV018", name: "D?ng b? Phu?ng Gi?ng V�" },
  { code: "DV019", name: "D?ng b? Phu?ng H� D�ng" },
  { code: "DV020", name: "D?ng b? Phu?ng Hai B� Trung" },
  { code: "DV021", name: "D?ng b? Phu?ng Ho�n Ki?m" },
  { code: "DV022", name: "D?ng b? Phu?ng Ho�ng Li?t" },
  { code: "DV023", name: "D?ng b? Phu?ng Ho�ng Mai" },
  { code: "DV024", name: "D?ng b? Phu?ng H?ng H�" },
  { code: "DV025", name: "D?ng b? Phu?ng Ki?n Hung" },
  { code: "DV026", name: "D?ng b? Phu?ng Kim Li�n" },
  { code: "DV027", name: "D?ng b? Phu?ng Khuong D�nh" },
  { code: "DV028", name: "D?ng b? Phu?ng L�ng" },
  { code: "DV029", name: "D?ng b? Phu?ng Linh Nam" },
  { code: "DV030", name: "D?ng b? Phu?ng Long Bi�n" },
  { code: "DV031", name: "D?ng b? Phu?ng Nghia D�" },
  { code: "DV032", name: "D?ng b? Phu?ng Ng?c H�" },
  { code: "DV033", name: "D?ng b? Phu?ng � Ch? D?a" },
  { code: "DV034", name: "D?ng b? Phu?ng Ph� Di?n" },
  { code: "DV035", name: "D?ng b? Phu?ng Ph� Luong" },
  { code: "DV036", name: "D?ng b? Phu?ng Ph� Thu?ng" },
  { code: "DV037", name: "D?ng b? Phu?ng Ph�c L?i" },
  { code: "DV038", name: "D?ng b? Phu?ng Phuong Li?t" },
  { code: "DV039", name: "D?ng b? Phu?ng Son T�y" },
  { code: "DV040", name: "D?ng b? Phu?ng T�y H?" },
  { code: "DV041", name: "D?ng b? Phu?ng T�y M?" },
  { code: "DV042", name: "D?ng b? Phu?ng T�y T?u" },
  { code: "DV043", name: "D?ng b? Phu?ng T�ng Thi?n" },
  { code: "DV044", name: "D?ng b? Phu?ng T? Li�m" },
  { code: "DV045", name: "D?ng b? Phu?ng Tuong Mai" },
  { code: "DV046", name: "D?ng b? Phu?ng Thanh Li?t" },
  { code: "DV047", name: "D?ng b? Phu?ng Thanh Xu�n" },
  { code: "DV048", name: "D?ng b? Phu?ng Thu?ng C�t" },
  { code: "DV049", name: "D?ng b? Phu?ng Van Mi?u-QTG" },
  { code: "DV050", name: "D?ng b? Phu?ng Vi?t Hung" },
  { code: "DV051", name: "D?ng b? Phu?ng Vinh Hung" },
  { code: "DV052", name: "D?ng b? Phu?ng Vinh Tuy" },
  { code: "DV053", name: "D?ng b? Phu?ng Xu�n D?nh" },
  { code: "DV054", name: "D?ng b? Phu?ng Xu�n Phuong" },
  { code: "DV055", name: "D?ng b? Phu?ng Y�n Ho�" },
  { code: "DV056", name: "D?ng b? Phu?ng Y�n Nghia" },
  { code: "DV057", name: "D?ng b? Phu?ng Y�n S?" },
  { code: "DV058", name: "D?ng b? X� An Kh�nh" },
  { code: "DV059", name: "D?ng b? X� Ba V�" },
  { code: "DV060", name: "D?ng b? X� B�t Tr�ng" },
  { code: "DV061", name: "D?ng b? X� B?t B?t" },
  { code: "DV062", name: "D?ng b? X� B�nh Minh" },
  { code: "DV063", name: "D?ng b? X� C? D�" },
  { code: "DV064", name: "D?ng b? X� Chuy�n M?" },
  { code: "DV065", name: "D?ng b? X� Chuong Duong" },
  { code: "DV066", name: "D?ng b? X� D�n Ho�" },
  { code: "DV067", name: "D?ng b? X� Duong H�a" },
  { code: "DV068", name: "D?ng b? X� Da Ph�c" },
  { code: "DV069", name: "D?ng b? X� D?i Thanh" },
  { code: "DV070", name: "D?ng b? X� D?i Xuy�n" },
  { code: "DV071", name: "D?ng b? X� Dan Phu?ng" },
  { code: "DV072", name: "D?ng b? x� Do�i Phuong" },
  { code: "DV073", name: "D?ng b? X� D�ng Anh" },
  { code: "DV074", name: "D?ng b? X� Gia L�m" },
  { code: "DV075", name: "D?ng b? X� H? B?ng" },
  { code: "DV076", name: "D?ng b? X� H�t M�n" },
  { code: "DV077", name: "D?ng b? X� Ho� L?c" },
  { code: "DV078", name: "D?ng b? X� Ho� Ph�" },
  { code: "DV079", name: "D?ng b? X� Ho� X�" },
  { code: "DV080", name: "D?ng b? X� Ho�i D?c" },
  { code: "DV081", name: "D?ng b? X� H?ng Son" },
  { code: "DV082", name: "D?ng b? X� H?ng V�n" },
  { code: "DV083", name: "D?ng b? X� Hung D?o" },
  { code: "DV084", name: "D?ng b? X� Huong Son" },
  { code: "DV085", name: "D?ng b? X� Ki?u Ph�" },
  { code: "DV086", name: "D?ng b? X� Kim Anh" },
  { code: "DV087", name: "D?ng b? X� Li�n Minh" },
  { code: "DV088", name: "D?ng b? X� M� Linh" },
  { code: "DV089", name: "D?ng b? X� Minh Ch�u" },
  { code: "DV090", name: "D?ng b? X� M? D?c" },
  { code: "DV091", name: "D?ng b? X� Nam Ph�" },
  { code: "DV092", name: "D?ng b? X� N?i B�i" },
  { code: "DV093", name: "D?ng b? X� Ng?c H?i" },
  { code: "DV094", name: "D?ng b? X� � Di�n" },
  { code: "DV095", name: "D?ng b? X� Ph� C�t" },
  { code: "DV096", name: "D?ng b? X� Ph� D?ng" },
  { code: "DV097", name: "D?ng b? X� Ph� Nghia" },
  { code: "DV098", name: "D?ng b? X� Ph� Xuy�n" },
  { code: "DV099", name: "D?ng b? X� Ph�c L?c" },
  { code: "DV100", name: "D?ng b? X� Ph�c Son" },
  { code: "DV101", name: "D?ng b? X� Ph�c Th?nh" },
  { code: "DV102", name: "D?ng b? X� Ph�c Th?" },
  { code: "DV103", name: "D?ng b? X� Phu?ng D?c" },
  { code: "DV104", name: "D?ng b? X� Qu?ng B?" },
  { code: "DV105", name: "D?ng b? X� Quang Minh" },
  { code: "DV106", name: "D?ng b? X� Qu?ng Oai" },
  { code: "DV107", name: "D?ng b? X� Qu?c Oai" },
  { code: "DV108", name: "D?ng b? X� S�c Son" },
  { code: "DV109", name: "D?ng b? X� Son D?ng" },
  { code: "DV110", name: "D?ng b? X� Su?i Hai" },
  { code: "DV111", name: "D?ng b? X� Tam Hung" },
  { code: "DV112", name: "D?ng b? X� T�y Phuong" },
  { code: "DV113", name: "D?ng b? X� Ti?n Th?ng" },
  { code: "DV114", name: "D?ng b? X� Th?ch Th?t" },
  { code: "DV115", name: "D?ng b? X� Thanh Oai" },
  { code: "DV116", name: "D?ng b? X� Thanh Tr�" },
  { code: "DV117", name: "D?ng b? X� Thi�n L?c" },
  { code: "DV118", name: "D?ng b? X� Thu?n An" },
  { code: "DV119", name: "D?ng b? X� Thu L�m" },
  { code: "DV120", name: "D?ng b? X� Thu?ng Ph�c" },
  { code: "DV121", name: "D?ng b? X� Thu?ng T�n" },
  { code: "DV122", name: "D?ng b? X� Tr?n Ph�" },
  { code: "DV123", name: "D?ng b? X� Trung Gi�" },
  { code: "DV124", name: "D?ng b? X� ?ng Ho�" },
  { code: "DV125", name: "D?ng b? X� ?ng Thi�n" },
  { code: "DV126", name: "D?ng b? X� V�n D�nh" },
  { code: "DV127", name: "D?ng b? X� V?t L?i" },
  { code: "DV128", name: "D?ng b? X� Vinh Thanh" },
  { code: "DV129", name: "D?ng b? X� Xu�n Mai" },
  { code: "DV130", name: "D?ng b? X� Y�n B�i" },
  { code: "DV131", name: "D?ng b? X� Y�n L�ng" },
  { code: "DV132", name: "D?ng b? X� Y�n Xu�n" },
];

export const YEARS = ["2024", "2025", "2026", "2027", "2028"];

export const DEFAULT_REPORTING_YEAR = "2026";

export const DEFAULT_PROJECT_ID = "proj_nq22";
export const DEFAULT_PROJECT_NAME = "T?ng h?p NQ22";

